; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	x
PUBLIC	y
PUBLIC	sum
_BSS	SEGMENT
sum	DD	01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
x	DD	01H
y	DD	02H
_DATA	ENDS
PUBLIC	main
; Function compile flags: /Odtp
_TEXT	SEGMENT
main	PROC
; File C:\Code\CSCI247\Code\C_Examples\ReadWriteGlobalVariables_64_Bit\Program.c
; Line 7
	mov	eax, DWORD PTR y
	mov	ecx, DWORD PTR x
	add	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR sum, eax
; Line 9
	mov	eax, DWORD PTR sum
; Line 10
	ret	0
main	ENDP
_TEXT	ENDS
END
